name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v \
            -keystore release.keystore \
            -alias mykey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=App, OU=Dev, O=Dev, L=City, S=State, C=FR" \
            -storepass 4MaboI1YxIMQzfQDfo0STSK8QN0ZSF9D \
            -keypass 4MaboI1YxIMQzfQDfo0STSK8QN0ZSF9D

      - name: Print base64
        run: base64 release.keystore